travis:
  secure:
    BINSTAR_TOKEN: Fa3kzPSKTBmAZeov/nsaf1Zcy6od55bGiy9NoiPb+bBd2ldoQN0lKLDpoSQ31EaBssJ4RgGPQ/RbqPhNTMOB6ZIRhqRA7Uo5zcecszRlOjVEmURVhDJHZL1hh2HqfIebzThazEYyMuVr0QW5QTX7x4BTiwKweKfitza24Avhr8bnQoKqu5D5GCfwAbkvyu5vxBZCPBJfNiAyDGqtDxo/yja28EzFOO7gzpSH50JiVwsHELcEpGXi3vZ9QlhwRuoI5bHGyVjqIM8XIYXEwNNwLn7EaDKSFur5ZhrIP4SqZimtixVcfKA2HStMbUM3nlGVb+acJixS+Dnnq/qHSxdDfw21eDEs8W2gTars/k0va7w66Mk1hkodnG58dZ7+v4DjpEBS38B1xv8uU+wCK/tQQLNBAaUUWX7rJpQwqZBjBxvuexzkcsWUbbkjg5ILEJJ+yRAReRBz8y8QzMJXHEz+a4TRz6jAEvWqvpa5cnQW+OR1oeEzNtxjq6bvsxwtduRDSK03l6f4U/ubjoPUudVUDKiaoT08IAvDfudbtc68madvXtLHFEvceX/AUGK+eBNOyicnHnyYSXIZ5hbEk/kLwjFT1dJINo9VS/Ujn5HGvGpZiYt5y+JnUWyVqMwLGCtDWg8XILOu/g160WoqX9ob74tz324bkMjD/hP896W/diI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
