travis:
  secure:
    BINSTAR_TOKEN: g30DAJfHjneb3nS+yZFTAyOKL/lD+tGyfzuxWAB7ky8hDL0QBZkJwUkgOE9cA0kOxCEPv+PuVlhjc0DMKtqmEpoOliWVEFOC/m8GjdMFZ2GCxp6g2LvT3/DBjFhklAicdtKU+96r7b3VNcAUYC1xhg2XNanRXEf/mXz3auwUJg+EDlKsG8I4fww06BlkiNqXMmP+31FW5e41U3oEbZN/vIZU1XGmwpQ93IxdxuTfn826lH3ZyK5B2lJMopzBuez3aVy2wosMFWjnwW9VJBvl1buUXXi7O6mUx7qySTpcxKfXw+6PPxAkpvSqZ1BPaCZFlrpOSuFqrHBK6C+UU9s5t0rB+CFU9IbTWU4svIA+fZGNoFz8B+c6uh7LxQM64GjYfeTQ1iEItN5oOPtbBeFmwXYNgS3weRPiV2hteXNuvqyoMo51fQIBfZMCae4HkcRB32/z9KDqrDJ/zODDeIexbabG1e4mK9674fFq0spny/LjW8hZIf3qdW3UDRVUf5S05Qj+0Ppj3/yZWME4YZpY+/6r0jmmx8p+AR7BxfxX0k7CoC5x9SwuwNZArKlIseT0XUKLdbNypagKbt8AJqB7vLOaYmq+hgi9iUVHxQxQVwz7EUBiEKFlJSlwlvytbpj5KjDKOPeHmekiE7dVlTVo7YTROkzT5wF2MpJ6TYwA+XY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
