travis:
  secure:
    BINSTAR_TOKEN: nUl8dwi8LGg3CkTSNMF6EIN8RTqbymJEPgLPW6rr8+Cn2zOxiTg5/JSIU0jZEoyHt25SUUXilImdPZyHhqb9a7snRy4qaw5M5Gcq35yjhChAZKNY6tvjgZj6eWn1KhQhAF4WdbySstjUqnKYGCfQGCTsKJcOnoXNSTxs80I/bCna4qvr1ZbwH77b29Sk5wG61SOsA5wJzdf1s2ZDlWnbYWIg/KUYp9BHNhE8+AMgBJtArI6g5WGDaLy+u12jGbKt586KN0CnTC3kZUwQPx77eE4IhiQPufLsbXbbYcN6GhOf/jliIFZB0EzJRjDhEwY/pdGkH+mM1k1risOs8J+h2rtw9PNiY+w5rJv+DTtgG7ZMjR0hxGeDvwgS1o93MhsQH1eLBSem2rbeUPIxIr21OQnTVtfw3lx5Mu5/lTHMV6RuNcGXaTxoZyc7IV6gGL9vsByInGgZd/jkTWPDhzCWfzNkK/f0w8s/hGIbgcvy/EXWSu+y3Acn+TktamJ98beGyLCBfDJsIc9R/CTynd/q2xFr4Xjeoim8gLLAm1vtxwnhWuatrXUAscodINwa0gmEd9sz0Eiu/QOI2dmfR1FSwudM2NWtOq5DKH3rAi9sk+gvUx58jWaSMlxBuBH869ouX0ljvRuTBvsONgXeJG9cqAK+Rq4hHRk+d1IVlqwmWbA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
